# syntax=docker/dockerfile:1
FROM golang:1.17-buster

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o test

COPY wait-for-it.sh ./
RUN chmod +x wait-for-it.sh

CMD ./wait-for-it.sh bidding:8080/health -- sleep 10 && ./test