FROM python:3.10-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
COPY ci/requirements.test.txt ./
COPY ci/wait-for-it.sh ./
COPY tests/test_integration.py ./tests/
RUN chmod +x wait-for-it.sh
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.test.txt
CMD ./wait-for-it.sh rabbitmq:5672 -t 30 -- python -m pytest tests/test_integration.py
